version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345678
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
  pg_data: